# Generated by Django 2.2.13 on 2020-07-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_remove_wallet_claim_count'),
        ('verification', '0005_auto_20200721_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyverification',
            name='receiving_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_claims', to='wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='receiving_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_claims', to='wallet.Wallet'),
        ),
        migrations.AlterField(
            model_name='companyverification',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Claimed'), (3, 'Requested'), (4, 'Claim limit reached'), (5, 'Tried to claim again')], default=1),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Claimed'), (3, 'Requested'), (4, 'Claim limit reached'), (5, 'Tried to claim again')], default=1),
        ),
        migrations.AlterField(
            model_name='verificationentry',
            name='state',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Claimed'), (3, 'Requested'), (4, 'Claim limit reached'), (5, 'Tried to claim again')], default=1),
        ),
    ]
